"""
Shelf sweeps: collect every product on a shop shelf from the shelf's own listing.

The rules live in markets/<market>/sweeps.json and are generated by build_sweeps.py.
Swept products get the id "<store>-<sku>", which is stable for as long as the
shop keeps the product.
"""
import json

from tracker.markets import STORES, Market


def run(rule: dict) -> list[dict]:
    """The rule's rows, refused when the shelf came back suspiciously empty."""
    rows = STORES[rule["store"]].scraper.sweep_rows(rule)
    minimum = rule.get("min_products", 0)
    if len(rows) < minimum:
        raise RuntimeError(f"sweep {rule['name']!r} returned {len(rows)} products, expected >= {minimum}")
    return rows


def load_rules(market: Market) -> list[dict]:
    path = market.config / "sweeps.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else []
